language: python

os:
  - linux

python:
  - "2.7"
  - "3.4"

branches:
  only:
    - master
    - development

install:
    - cd python
    - pip install coverage
    - pip install python-coveralls
    - pip install -r requirements.txt
    - pip install -e .

script:
    - cd wfnsympy
    - cd unittest
    - coverage run --source=../ -m unittest discover . "test_*.py"

after_success:
    - coveralls
    - cd ../..
