/* File: QSYMLIBmodule.c
 * This file is auto-generated with f2py (version:2.4.2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Sun Mar  8 19:50:24 2026
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *QSYMLIB_error;
static PyObject *QSYMLIB_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(QSYMLIB_error,errstring);\
        /*goto capi_fail;*/\
    } else 

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = QSYMLIB_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = QSYMLIB_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(denslib,DENSLIB)(double*,double*,int*,int*,int*,int*,int*,double*,double*,double*,int*,int*,double*,double*,string*,double*,size_t);
extern void F_FUNC_US(center_charge,CENTER_CHARGE)(double*,int*,double*,double*,int*,double*,double*,int*);
extern void F_FUNC_US(build_density,BUILD_DENSITY)(double*,int*,double*,double*,int*,int*,int*,double*,int*,int*,int*,double*,double*,int*,double*,double*,double*,int*,int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** denslib **********************************/
static char doc_f2py_rout_QSYMLIB_denslib[] = "\
OutDim,OutCSM_i,OutCSM,OutSymLab,OutSsimilarity = denslib(vaxis_2,vaxis2_2,norbx,igroup,ngroup,dooper,iangdens,alphdens,cdens,rdens,[ndens])\n\nWrapper for ``denslib``.\
\n\nParameters\n----------\n"
"vaxis_2 : input rank-1 array('d') with bounds (3)\n"
"vaxis2_2 : input rank-1 array('d') with bounds (3)\n"
"norbx : input int\n"
"igroup : input int\n"
"ngroup : input int\n"
"dooper : input int\n"
"iangdens : input rank-2 array('i') with bounds (ndens,3)\n"
"alphdens : input rank-1 array('d') with bounds (ndens)\n"
"cdens : input rank-1 array('d') with bounds (ndens)\n"
"rdens : input rank-2 array('d') with bounds (ndens,3)\n"
"\nOther Parameters\n----------------\n"
"ndens : input int, optional\n    Default: len(alphdens)\n"
"\nReturns\n-------\n"
"OutDim : rank-1 array('i') with bounds (3)\n"
"OutCSM_i : rank-1 array('d') with bounds (100)\n"
"OutCSM : float\n"
"OutSymLab : rank-1 array('S') with bounds (100)\n"
"OutSsimilarity : float";
/* extern void F_FUNC(denslib,DENSLIB)(double*,double*,int*,int*,int*,int*,int*,double*,double*,double*,int*,int*,double*,double*,string*,double*,size_t); */
static PyObject *f2py_rout_QSYMLIB_denslib(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,int*,int*,int*,int*,double*,double*,double*,int*,int*,double*,double*,string*,double*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *vaxis_2 = NULL;
    npy_intp vaxis_2_Dims[1] = {-1};
    const int vaxis_2_Rank = 1;
    PyArrayObject *capi_vaxis_2_as_array = NULL;
    int capi_vaxis_2_intent = 0;
    PyObject *vaxis_2_capi = Py_None;
    double *vaxis2_2 = NULL;
    npy_intp vaxis2_2_Dims[1] = {-1};
    const int vaxis2_2_Rank = 1;
    PyArrayObject *capi_vaxis2_2_as_array = NULL;
    int capi_vaxis2_2_intent = 0;
    PyObject *vaxis2_2_capi = Py_None;
    int norbx = 0;
    PyObject *norbx_capi = Py_None;
    int igroup = 0;
    PyObject *igroup_capi = Py_None;
    int ngroup = 0;
    PyObject *ngroup_capi = Py_None;
    int dooper = 0;
    PyObject *dooper_capi = Py_None;
    int *iangdens = NULL;
    npy_intp iangdens_Dims[2] = {-1, -1};
    const int iangdens_Rank = 2;
    PyArrayObject *capi_iangdens_as_array = NULL;
    int capi_iangdens_intent = 0;
    PyObject *iangdens_capi = Py_None;
    double *alphdens = NULL;
    npy_intp alphdens_Dims[1] = {-1};
    const int alphdens_Rank = 1;
    PyArrayObject *capi_alphdens_as_array = NULL;
    int capi_alphdens_intent = 0;
    PyObject *alphdens_capi = Py_None;
    double *cdens = NULL;
    npy_intp cdens_Dims[1] = {-1};
    const int cdens_Rank = 1;
    PyArrayObject *capi_cdens_as_array = NULL;
    int capi_cdens_intent = 0;
    PyObject *cdens_capi = Py_None;
    double *rdens = NULL;
    npy_intp rdens_Dims[2] = {-1, -1};
    const int rdens_Rank = 2;
    PyArrayObject *capi_rdens_as_array = NULL;
    int capi_rdens_intent = 0;
    PyObject *rdens_capi = Py_None;
    int ndens = 0;
    PyObject *ndens_capi = Py_None;
    int *OutDim = NULL;
    npy_intp OutDim_Dims[1] = {-1};
    const int OutDim_Rank = 1;
    PyArrayObject *capi_OutDim_as_array = NULL;
    int capi_OutDim_intent = 0;
    double *OutCSM_i = NULL;
    npy_intp OutCSM_i_Dims[1] = {-1};
    const int OutCSM_i_Rank = 1;
    PyArrayObject *capi_OutCSM_i_as_array = NULL;
    int capi_OutCSM_i_intent = 0;
    double OutCSM = 0;
    string *OutSymLab = NULL;
    npy_intp OutSymLab_Dims[1] = {-1};
    const int OutSymLab_Rank = 1;
    PyArrayObject *capi_OutSymLab_as_array = NULL;
    int capi_OutSymLab_intent = 0;
    int slen(OutSymLab) = 0;
    double OutSsimilarity = 0;
    static char *capi_kwlist[] = {"vaxis_2","vaxis2_2","norbx","igroup","ngroup","dooper","iangdens","alphdens","cdens","rdens","ndens",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOO|O:QSYMLIB.denslib",\
        capi_kwlist,&vaxis_2_capi,&vaxis2_2_capi,&norbx_capi,&igroup_capi,&ngroup_capi,&dooper_capi,&iangdens_capi,&alphdens_capi,&cdens_capi,&rdens_capi,&ndens_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable norbx */
        f2py_success = int_from_pyobj(&norbx,norbx_capi,"QSYMLIB.denslib() 3rd argument (norbx) can't be converted to int");
    if (f2py_success) {
    /* Processing variable igroup */
        f2py_success = int_from_pyobj(&igroup,igroup_capi,"QSYMLIB.denslib() 4th argument (igroup) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ngroup */
        f2py_success = int_from_pyobj(&ngroup,ngroup_capi,"QSYMLIB.denslib() 5th argument (ngroup) can't be converted to int");
    if (f2py_success) {
    /* Processing variable vaxis_2 */
    vaxis_2_Dims[0]=3;
    capi_vaxis_2_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.denslib: failed to create array from the 1st argument `vaxis_2`";
    capi_vaxis_2_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,vaxis_2_Dims,vaxis_2_Rank,  capi_vaxis_2_intent,vaxis_2_capi,capi_errmess);
    if (capi_vaxis_2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        vaxis_2 = (double *)(PyArray_DATA(capi_vaxis_2_as_array));

    /* Processing variable vaxis2_2 */
    vaxis2_2_Dims[0]=3;
    capi_vaxis2_2_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.denslib: failed to create array from the 2nd argument `vaxis2_2`";
    capi_vaxis2_2_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,vaxis2_2_Dims,vaxis2_2_Rank,  capi_vaxis2_2_intent,vaxis2_2_capi,capi_errmess);
    if (capi_vaxis2_2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        vaxis2_2 = (double *)(PyArray_DATA(capi_vaxis2_2_as_array));

    /* Processing variable dooper */
        dooper = (int)PyObject_IsTrue(dooper_capi);
        f2py_success = 1;
    if (f2py_success) {
    /* Processing variable OutDim */
    OutDim_Dims[0]=3;
    capi_OutDim_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.denslib: failed to create array from the hidden `OutDim`";
    capi_OutDim_as_array = ndarray_from_pyobj(  NPY_INT,1,OutDim_Dims,OutDim_Rank,  capi_OutDim_intent,Py_None,capi_errmess);
    if (capi_OutDim_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutDim = (int *)(PyArray_DATA(capi_OutDim_as_array));

    /* Processing variable OutCSM_i */
    OutCSM_i_Dims[0]=100;
    capi_OutCSM_i_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.denslib: failed to create array from the hidden `OutCSM_i`";
    capi_OutCSM_i_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,OutCSM_i_Dims,OutCSM_i_Rank,  capi_OutCSM_i_intent,Py_None,capi_errmess);
    if (capi_OutCSM_i_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutCSM_i = (double *)(PyArray_DATA(capi_OutCSM_i_as_array));

    /* Processing variable OutCSM */
    /* Processing variable OutSsimilarity */
    /* Processing variable OutSymLab */
    OutSymLab_Dims[0]=100;
    capi_OutSymLab_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.denslib: failed to create array from the hidden `OutSymLab`";
    capi_OutSymLab_as_array = ndarray_from_pyobj(  NPY_STRING,6,OutSymLab_Dims,OutSymLab_Rank,  capi_OutSymLab_intent,Py_None,capi_errmess);
    if (capi_OutSymLab_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutSymLab = (string *)(PyArray_DATA(capi_OutSymLab_as_array));

    slen(OutSymLab) = f2py_itemsize(OutSymLab);
    /* Processing variable alphdens */
    ;
    capi_alphdens_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.denslib: failed to create array from the 8th argument `alphdens`";
    capi_alphdens_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,alphdens_Dims,alphdens_Rank,  capi_alphdens_intent,alphdens_capi,capi_errmess);
    if (capi_alphdens_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        alphdens = (double *)(PyArray_DATA(capi_alphdens_as_array));

    /* Processing variable iangdens */
    iangdens_Dims[1]=3;
    capi_iangdens_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.denslib: failed to create array from the 7th argument `iangdens`";
    capi_iangdens_as_array = ndarray_from_pyobj(  NPY_INT,1,iangdens_Dims,iangdens_Rank,  capi_iangdens_intent,iangdens_capi,capi_errmess);
    if (capi_iangdens_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        iangdens = (int *)(PyArray_DATA(capi_iangdens_as_array));

    /* Processing variable rdens */
    rdens_Dims[1]=3;
    capi_rdens_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.denslib: failed to create array from the 10th argument `rdens`";
    capi_rdens_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,rdens_Dims,rdens_Rank,  capi_rdens_intent,rdens_capi,capi_errmess);
    if (capi_rdens_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        rdens = (double *)(PyArray_DATA(capi_rdens_as_array));

    /* Processing variable cdens */
    ;
    capi_cdens_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.denslib: failed to create array from the 9th argument `cdens`";
    capi_cdens_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,cdens_Dims,cdens_Rank,  capi_cdens_intent,cdens_capi,capi_errmess);
    if (capi_cdens_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cdens = (double *)(PyArray_DATA(capi_cdens_as_array));

    /* Processing variable ndens */
    if (ndens_capi == Py_None) ndens = len(alphdens); else
        f2py_success = int_from_pyobj(&ndens,ndens_capi,"QSYMLIB.denslib() 1st keyword (ndens) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(alphdens)>=ndens,"len(alphdens)>=ndens","1st keyword ndens","denslib:ndens=%d",ndens) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(vaxis_2,vaxis2_2,&norbx,&igroup,&ngroup,&dooper,iangdens,alphdens,cdens,rdens,&ndens,OutDim,OutCSM_i,&OutCSM,OutSymLab,&OutSsimilarity,slen(OutSymLab));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NNdNd",capi_OutDim_as_array,capi_OutCSM_i_as_array,OutCSM,capi_OutSymLab_as_array,OutSsimilarity);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(len(alphdens)>=ndens)*/
    } /*if (f2py_success) of ndens*/
    /* End of cleaning variable ndens */
    if((PyObject *)capi_cdens_as_array!=cdens_capi) {
        Py_XDECREF(capi_cdens_as_array); }
    }  /* if (capi_cdens_as_array == NULL) ... else of cdens */
    /* End of cleaning variable cdens */
    if((PyObject *)capi_rdens_as_array!=rdens_capi) {
        Py_XDECREF(capi_rdens_as_array); }
    }  /* if (capi_rdens_as_array == NULL) ... else of rdens */
    /* End of cleaning variable rdens */
    if((PyObject *)capi_iangdens_as_array!=iangdens_capi) {
        Py_XDECREF(capi_iangdens_as_array); }
    }  /* if (capi_iangdens_as_array == NULL) ... else of iangdens */
    /* End of cleaning variable iangdens */
    if((PyObject *)capi_alphdens_as_array!=alphdens_capi) {
        Py_XDECREF(capi_alphdens_as_array); }
    }  /* if (capi_alphdens_as_array == NULL) ... else of alphdens */
    /* End of cleaning variable alphdens */
    }  /* if (capi_OutSymLab_as_array == NULL) ... else of OutSymLab */
    /* End of cleaning variable OutSymLab */
    /* End of cleaning variable OutSsimilarity */
    /* End of cleaning variable OutCSM */
    }  /* if (capi_OutCSM_i_as_array == NULL) ... else of OutCSM_i */
    /* End of cleaning variable OutCSM_i */
    }  /* if (capi_OutDim_as_array == NULL) ... else of OutDim */
    /* End of cleaning variable OutDim */
    } /*if (f2py_success) of dooper*/
    /* End of cleaning variable dooper */
    if((PyObject *)capi_vaxis2_2_as_array!=vaxis2_2_capi) {
        Py_XDECREF(capi_vaxis2_2_as_array); }
    }  /* if (capi_vaxis2_2_as_array == NULL) ... else of vaxis2_2 */
    /* End of cleaning variable vaxis2_2 */
    if((PyObject *)capi_vaxis_2_as_array!=vaxis_2_capi) {
        Py_XDECREF(capi_vaxis_2_as_array); }
    }  /* if (capi_vaxis_2_as_array == NULL) ... else of vaxis_2 */
    /* End of cleaning variable vaxis_2 */
    } /*if (f2py_success) of ngroup*/
    /* End of cleaning variable ngroup */
    } /*if (f2py_success) of igroup*/
    /* End of cleaning variable igroup */
    } /*if (f2py_success) of norbx*/
    /* End of cleaning variable norbx */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of denslib *******************************/

/******************************* center_charge *******************************/
static char doc_f2py_rout_QSYMLIB_center_charge[] = "\
elec_total,outrc = center_charge(alphdens,iangdens,rdens,cdens,n_elec,[ndens])\n\nWrapper for ``center_charge``.\
\n\nParameters\n----------\n"
"alphdens : input rank-1 array('d') with bounds (ndens)\n"
"iangdens : input rank-2 array('i') with bounds (ndens,3)\n"
"rdens : input rank-2 array('d') with bounds (ndens,3)\n"
"cdens : input rank-1 array('d') with bounds (ndens)\n"
"n_elec : input int\n"
"\nOther Parameters\n----------------\n"
"ndens : input int, optional\n    Default: len(alphdens)\n"
"\nReturns\n-------\n"
"elec_total : float\n"
"outrc : rank-1 array('d') with bounds (3)";
/* extern void F_FUNC_US(center_charge,CENTER_CHARGE)(double*,int*,double*,double*,int*,double*,double*,int*); */
static PyObject *f2py_rout_QSYMLIB_center_charge(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,double*,double*,int*,double*,double*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *alphdens = NULL;
    npy_intp alphdens_Dims[1] = {-1};
    const int alphdens_Rank = 1;
    PyArrayObject *capi_alphdens_as_array = NULL;
    int capi_alphdens_intent = 0;
    PyObject *alphdens_capi = Py_None;
    int *iangdens = NULL;
    npy_intp iangdens_Dims[2] = {-1, -1};
    const int iangdens_Rank = 2;
    PyArrayObject *capi_iangdens_as_array = NULL;
    int capi_iangdens_intent = 0;
    PyObject *iangdens_capi = Py_None;
    double *rdens = NULL;
    npy_intp rdens_Dims[2] = {-1, -1};
    const int rdens_Rank = 2;
    PyArrayObject *capi_rdens_as_array = NULL;
    int capi_rdens_intent = 0;
    PyObject *rdens_capi = Py_None;
    double *cdens = NULL;
    npy_intp cdens_Dims[1] = {-1};
    const int cdens_Rank = 1;
    PyArrayObject *capi_cdens_as_array = NULL;
    int capi_cdens_intent = 0;
    PyObject *cdens_capi = Py_None;
    int n_elec = 0;
    PyObject *n_elec_capi = Py_None;
    double elec_total = 0;
    double *outrc = NULL;
    npy_intp outrc_Dims[1] = {-1};
    const int outrc_Rank = 1;
    PyArrayObject *capi_outrc_as_array = NULL;
    int capi_outrc_intent = 0;
    int ndens = 0;
    PyObject *ndens_capi = Py_None;
    static char *capi_kwlist[] = {"alphdens","iangdens","rdens","cdens","n_elec","ndens",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOO|O:QSYMLIB.center_charge",\
        capi_kwlist,&alphdens_capi,&iangdens_capi,&rdens_capi,&cdens_capi,&n_elec_capi,&ndens_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable n_elec */
        f2py_success = int_from_pyobj(&n_elec,n_elec_capi,"QSYMLIB.center_charge() 5th argument (n_elec) can't be converted to int");
    if (f2py_success) {
    /* Processing variable elec_total */
    /* Processing variable outrc */
    outrc_Dims[0]=3;
    capi_outrc_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.center_charge: failed to create array from the hidden `outrc`";
    capi_outrc_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,outrc_Dims,outrc_Rank,  capi_outrc_intent,Py_None,capi_errmess);
    if (capi_outrc_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        outrc = (double *)(PyArray_DATA(capi_outrc_as_array));

    /* Processing variable alphdens */
    ;
    capi_alphdens_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.center_charge: failed to create array from the 1st argument `alphdens`";
    capi_alphdens_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,alphdens_Dims,alphdens_Rank,  capi_alphdens_intent,alphdens_capi,capi_errmess);
    if (capi_alphdens_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        alphdens = (double *)(PyArray_DATA(capi_alphdens_as_array));

    /* Processing variable iangdens */
    iangdens_Dims[1]=3;
    capi_iangdens_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.center_charge: failed to create array from the 2nd argument `iangdens`";
    capi_iangdens_as_array = ndarray_from_pyobj(  NPY_INT,1,iangdens_Dims,iangdens_Rank,  capi_iangdens_intent,iangdens_capi,capi_errmess);
    if (capi_iangdens_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        iangdens = (int *)(PyArray_DATA(capi_iangdens_as_array));

    /* Processing variable rdens */
    rdens_Dims[1]=3;
    capi_rdens_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.center_charge: failed to create array from the 3rd argument `rdens`";
    capi_rdens_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,rdens_Dims,rdens_Rank,  capi_rdens_intent,rdens_capi,capi_errmess);
    if (capi_rdens_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        rdens = (double *)(PyArray_DATA(capi_rdens_as_array));

    /* Processing variable cdens */
    ;
    capi_cdens_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.center_charge: failed to create array from the 4th argument `cdens`";
    capi_cdens_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,cdens_Dims,cdens_Rank,  capi_cdens_intent,cdens_capi,capi_errmess);
    if (capi_cdens_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cdens = (double *)(PyArray_DATA(capi_cdens_as_array));

    /* Processing variable ndens */
    if (ndens_capi == Py_None) ndens = len(alphdens); else
        f2py_success = int_from_pyobj(&ndens,ndens_capi,"QSYMLIB.center_charge() 1st keyword (ndens) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(alphdens)>=ndens,"len(alphdens)>=ndens","1st keyword ndens","center_charge:ndens=%d",ndens) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(alphdens,iangdens,rdens,cdens,&n_elec,&elec_total,outrc,&ndens);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("dN",elec_total,capi_outrc_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(len(alphdens)>=ndens)*/
    } /*if (f2py_success) of ndens*/
    /* End of cleaning variable ndens */
    if((PyObject *)capi_cdens_as_array!=cdens_capi) {
        Py_XDECREF(capi_cdens_as_array); }
    }  /* if (capi_cdens_as_array == NULL) ... else of cdens */
    /* End of cleaning variable cdens */
    if((PyObject *)capi_rdens_as_array!=rdens_capi) {
        Py_XDECREF(capi_rdens_as_array); }
    }  /* if (capi_rdens_as_array == NULL) ... else of rdens */
    /* End of cleaning variable rdens */
    if((PyObject *)capi_iangdens_as_array!=iangdens_capi) {
        Py_XDECREF(capi_iangdens_as_array); }
    }  /* if (capi_iangdens_as_array == NULL) ... else of iangdens */
    /* End of cleaning variable iangdens */
    if((PyObject *)capi_alphdens_as_array!=alphdens_capi) {
        Py_XDECREF(capi_alphdens_as_array); }
    }  /* if (capi_alphdens_as_array == NULL) ... else of alphdens */
    /* End of cleaning variable alphdens */
    }  /* if (capi_outrc_as_array == NULL) ... else of outrc */
    /* End of cleaning variable outrc */
    /* End of cleaning variable elec_total */
    } /*if (f2py_success) of n_elec*/
    /* End of cleaning variable n_elec */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************************** end of center_charge ****************************/

/******************************* build_density *******************************/
static char doc_f2py_rout_QSYMLIB_build_density[] = "\
iAngDens,AlphDens,CDens,RDens,NDens = build_density(r,ldens,alfa2,coef2,nprim,nshell,shell_type,coef_mol,nmos,naos,norbx,occupancy,TolDens,[norb,nat_2,ntotshell])\n\nWrapper for ``build_density``.\
\n\nParameters\n----------\n"
"r : input rank-2 array('d') with bounds (nat_2,3)\n"
"ldens : input int\n"
"alfa2 : input rank-1 array('d') with bounds (norb)\n"
"coef2 : input rank-1 array('d') with bounds (norb)\n"
"nprim : input rank-1 array('i') with bounds (ntotshell)\n"
"nshell : input rank-1 array('i') with bounds (nat_2)\n"
"shell_type : input rank-1 array('i') with bounds (ntotshell)\n"
"coef_mol : input rank-1 array('d') with bounds (naos * nmos)\n"
"nmos : input int\n"
"naos : input int\n"
"norbx : input int\n"
"occupancy : input rank-1 array('d') with bounds (nmos)\n"
"TolDens : input float\n"
"\nOther Parameters\n----------------\n"
"norb : input int, optional\n    Default: len(alfa2)\n"
"nat_2 : input int, optional\n    Default: shape(r,0)\n"
"ntotshell : input int, optional\n    Default: len(nprim)\n"
"\nReturns\n-------\n"
"iAngDens : rank-2 array('i') with bounds (ldens,3)\n"
"AlphDens : rank-1 array('d') with bounds (ldens)\n"
"CDens : rank-1 array('d') with bounds (ldens)\n"
"RDens : rank-2 array('d') with bounds (ldens,3)\n"
"NDens : int";
/* extern void F_FUNC_US(build_density,BUILD_DENSITY)(double*,int*,double*,double*,int*,int*,int*,double*,int*,int*,int*,double*,double*,int*,double*,double*,double*,int*,int*,int*,int*); */
static PyObject *f2py_rout_QSYMLIB_build_density(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,double*,double*,int*,int*,int*,double*,int*,int*,int*,double*,double*,int*,double*,double*,double*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *r = NULL;
    npy_intp r_Dims[2] = {-1, -1};
    const int r_Rank = 2;
    PyArrayObject *capi_r_as_array = NULL;
    int capi_r_intent = 0;
    PyObject *r_capi = Py_None;
    int ldens = 0;
    PyObject *ldens_capi = Py_None;
    double *alfa2 = NULL;
    npy_intp alfa2_Dims[1] = {-1};
    const int alfa2_Rank = 1;
    PyArrayObject *capi_alfa2_as_array = NULL;
    int capi_alfa2_intent = 0;
    PyObject *alfa2_capi = Py_None;
    double *coef2 = NULL;
    npy_intp coef2_Dims[1] = {-1};
    const int coef2_Rank = 1;
    PyArrayObject *capi_coef2_as_array = NULL;
    int capi_coef2_intent = 0;
    PyObject *coef2_capi = Py_None;
    int *nprim = NULL;
    npy_intp nprim_Dims[1] = {-1};
    const int nprim_Rank = 1;
    PyArrayObject *capi_nprim_as_array = NULL;
    int capi_nprim_intent = 0;
    PyObject *nprim_capi = Py_None;
    int *nshell = NULL;
    npy_intp nshell_Dims[1] = {-1};
    const int nshell_Rank = 1;
    PyArrayObject *capi_nshell_as_array = NULL;
    int capi_nshell_intent = 0;
    PyObject *nshell_capi = Py_None;
    int *shell_type = NULL;
    npy_intp shell_type_Dims[1] = {-1};
    const int shell_type_Rank = 1;
    PyArrayObject *capi_shell_type_as_array = NULL;
    int capi_shell_type_intent = 0;
    PyObject *shell_type_capi = Py_None;
    double *coef_mol = NULL;
    npy_intp coef_mol_Dims[1] = {-1};
    const int coef_mol_Rank = 1;
    PyArrayObject *capi_coef_mol_as_array = NULL;
    int capi_coef_mol_intent = 0;
    PyObject *coef_mol_capi = Py_None;
    int nmos = 0;
    PyObject *nmos_capi = Py_None;
    int naos = 0;
    PyObject *naos_capi = Py_None;
    int norbx = 0;
    PyObject *norbx_capi = Py_None;
    double *occupancy = NULL;
    npy_intp occupancy_Dims[1] = {-1};
    const int occupancy_Rank = 1;
    PyArrayObject *capi_occupancy_as_array = NULL;
    int capi_occupancy_intent = 0;
    PyObject *occupancy_capi = Py_None;
    double TolDens = 0;
    PyObject *TolDens_capi = Py_None;
    int *iAngDens = NULL;
    npy_intp iAngDens_Dims[2] = {-1, -1};
    const int iAngDens_Rank = 2;
    PyArrayObject *capi_iAngDens_as_array = NULL;
    int capi_iAngDens_intent = 0;
    double *AlphDens = NULL;
    npy_intp AlphDens_Dims[1] = {-1};
    const int AlphDens_Rank = 1;
    PyArrayObject *capi_AlphDens_as_array = NULL;
    int capi_AlphDens_intent = 0;
    double *CDens = NULL;
    npy_intp CDens_Dims[1] = {-1};
    const int CDens_Rank = 1;
    PyArrayObject *capi_CDens_as_array = NULL;
    int capi_CDens_intent = 0;
    double *RDens = NULL;
    npy_intp RDens_Dims[2] = {-1, -1};
    const int RDens_Rank = 2;
    PyArrayObject *capi_RDens_as_array = NULL;
    int capi_RDens_intent = 0;
    int NDens = 0;
    int norb = 0;
    PyObject *norb_capi = Py_None;
    int nat_2 = 0;
    PyObject *nat_2_capi = Py_None;
    int ntotshell = 0;
    PyObject *ntotshell_capi = Py_None;
    static char *capi_kwlist[] = {"r","ldens","alfa2","coef2","nprim","nshell","shell_type","coef_mol","nmos","naos","norbx","occupancy","TolDens","norb","nat_2","ntotshell",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOO|OOO:QSYMLIB.build_density",\
        capi_kwlist,&r_capi,&ldens_capi,&alfa2_capi,&coef2_capi,&nprim_capi,&nshell_capi,&shell_type_capi,&coef_mol_capi,&nmos_capi,&naos_capi,&norbx_capi,&occupancy_capi,&TolDens_capi,&norb_capi,&nat_2_capi,&ntotshell_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable r */
    r_Dims[1]=3;
    capi_r_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.build_density: failed to create array from the 1st argument `r`";
    capi_r_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,r_Dims,r_Rank,  capi_r_intent,r_capi,capi_errmess);
    if (capi_r_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        r = (double *)(PyArray_DATA(capi_r_as_array));

    /* Processing variable ldens */
        f2py_success = int_from_pyobj(&ldens,ldens_capi,"QSYMLIB.build_density() 2nd argument (ldens) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nprim */
    ;
    capi_nprim_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.build_density: failed to create array from the 5th argument `nprim`";
    capi_nprim_as_array = ndarray_from_pyobj(  NPY_INT,1,nprim_Dims,nprim_Rank,  capi_nprim_intent,nprim_capi,capi_errmess);
    if (capi_nprim_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        nprim = (int *)(PyArray_DATA(capi_nprim_as_array));

    /* Processing variable TolDens */
        f2py_success = double_from_pyobj(&TolDens,TolDens_capi,"QSYMLIB.build_density() 13rd argument (TolDens) can't be converted to double");
    if (f2py_success) {
    /* Processing variable nmos */
        f2py_success = int_from_pyobj(&nmos,nmos_capi,"QSYMLIB.build_density() 9th argument (nmos) can't be converted to int");
    if (f2py_success) {
    /* Processing variable naos */
        f2py_success = int_from_pyobj(&naos,naos_capi,"QSYMLIB.build_density() 10th argument (naos) can't be converted to int");
    if (f2py_success) {
    /* Processing variable norbx */
        f2py_success = int_from_pyobj(&norbx,norbx_capi,"QSYMLIB.build_density() 11st argument (norbx) can't be converted to int");
    if (f2py_success) {
    /* Processing variable NDens */
    /* Processing variable coef_mol */
    coef_mol_Dims[0]=naos * nmos;
    capi_coef_mol_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.build_density: failed to create array from the 8th argument `coef_mol`";
    capi_coef_mol_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,coef_mol_Dims,coef_mol_Rank,  capi_coef_mol_intent,coef_mol_capi,capi_errmess);
    if (capi_coef_mol_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        coef_mol = (double *)(PyArray_DATA(capi_coef_mol_as_array));

    /* Processing variable occupancy */
    occupancy_Dims[0]=nmos;
    capi_occupancy_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.build_density: failed to create array from the 12nd argument `occupancy`";
    capi_occupancy_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,occupancy_Dims,occupancy_Rank,  capi_occupancy_intent,occupancy_capi,capi_errmess);
    if (capi_occupancy_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        occupancy = (double *)(PyArray_DATA(capi_occupancy_as_array));

    /* Processing variable nat_2 */
    if (nat_2_capi == Py_None) nat_2 = shape(r,0); else
        f2py_success = int_from_pyobj(&nat_2,nat_2_capi,"QSYMLIB.build_density() 2nd keyword (nat_2) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(r,0)==nat_2,"shape(r,0)==nat_2","2nd keyword nat_2","build_density:nat_2=%d",nat_2) {
    /* Processing variable ntotshell */
    if (ntotshell_capi == Py_None) ntotshell = len(nprim); else
        f2py_success = int_from_pyobj(&ntotshell,ntotshell_capi,"QSYMLIB.build_density() 3rd keyword (ntotshell) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(nprim)>=ntotshell,"len(nprim)>=ntotshell","3rd keyword ntotshell","build_density:ntotshell=%d",ntotshell) {
    /* Processing variable iAngDens */
    iAngDens_Dims[0]=ldens,iAngDens_Dims[1]=3;
    capi_iAngDens_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.build_density: failed to create array from the hidden `iAngDens`";
    capi_iAngDens_as_array = ndarray_from_pyobj(  NPY_INT,1,iAngDens_Dims,iAngDens_Rank,  capi_iAngDens_intent,Py_None,capi_errmess);
    if (capi_iAngDens_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        iAngDens = (int *)(PyArray_DATA(capi_iAngDens_as_array));

    /* Processing variable RDens */
    RDens_Dims[0]=ldens,RDens_Dims[1]=3;
    capi_RDens_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.build_density: failed to create array from the hidden `RDens`";
    capi_RDens_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,RDens_Dims,RDens_Rank,  capi_RDens_intent,Py_None,capi_errmess);
    if (capi_RDens_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        RDens = (double *)(PyArray_DATA(capi_RDens_as_array));

    /* Processing variable AlphDens */
    AlphDens_Dims[0]=ldens;
    capi_AlphDens_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.build_density: failed to create array from the hidden `AlphDens`";
    capi_AlphDens_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,AlphDens_Dims,AlphDens_Rank,  capi_AlphDens_intent,Py_None,capi_errmess);
    if (capi_AlphDens_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        AlphDens = (double *)(PyArray_DATA(capi_AlphDens_as_array));

    /* Processing variable CDens */
    CDens_Dims[0]=ldens;
    capi_CDens_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.build_density: failed to create array from the hidden `CDens`";
    capi_CDens_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,CDens_Dims,CDens_Rank,  capi_CDens_intent,Py_None,capi_errmess);
    if (capi_CDens_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        CDens = (double *)(PyArray_DATA(capi_CDens_as_array));

    /* Processing variable nshell */
    nshell_Dims[0]=nat_2;
    capi_nshell_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.build_density: failed to create array from the 6th argument `nshell`";
    capi_nshell_as_array = ndarray_from_pyobj(  NPY_INT,1,nshell_Dims,nshell_Rank,  capi_nshell_intent,nshell_capi,capi_errmess);
    if (capi_nshell_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        nshell = (int *)(PyArray_DATA(capi_nshell_as_array));

    /* Processing variable shell_type */
    shell_type_Dims[0]=ntotshell;
    capi_shell_type_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.build_density: failed to create array from the 7th argument `shell_type`";
    capi_shell_type_as_array = ndarray_from_pyobj(  NPY_INT,1,shell_type_Dims,shell_type_Rank,  capi_shell_type_intent,shell_type_capi,capi_errmess);
    if (capi_shell_type_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        shell_type = (int *)(PyArray_DATA(capi_shell_type_as_array));

    /* Processing variable alfa2 */
    ;
    capi_alfa2_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.build_density: failed to create array from the 3rd argument `alfa2`";
    capi_alfa2_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,alfa2_Dims,alfa2_Rank,  capi_alfa2_intent,alfa2_capi,capi_errmess);
    if (capi_alfa2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        alfa2 = (double *)(PyArray_DATA(capi_alfa2_as_array));

    /* Processing variable coef2 */
    ;
    capi_coef2_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "QSYMLIB.QSYMLIB.build_density: failed to create array from the 4th argument `coef2`";
    capi_coef2_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,coef2_Dims,coef2_Rank,  capi_coef2_intent,coef2_capi,capi_errmess);
    if (capi_coef2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = QSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        coef2 = (double *)(PyArray_DATA(capi_coef2_as_array));

    /* Processing variable norb */
    if (norb_capi == Py_None) norb = len(alfa2); else
        f2py_success = int_from_pyobj(&norb,norb_capi,"QSYMLIB.build_density() 1st keyword (norb) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(alfa2)>=norb,"len(alfa2)>=norb","1st keyword norb","build_density:norb=%d",norb) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(r,&ldens,alfa2,coef2,nprim,nshell,shell_type,coef_mol,&nmos,&naos,&norbx,occupancy,&TolDens,iAngDens,AlphDens,CDens,RDens,&NDens,&norb,&nat_2,&ntotshell);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NNNNi",capi_iAngDens_as_array,capi_AlphDens_as_array,capi_CDens_as_array,capi_RDens_as_array,NDens);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(len(alfa2)>=norb)*/
    } /*if (f2py_success) of norb*/
    /* End of cleaning variable norb */
    if((PyObject *)capi_coef2_as_array!=coef2_capi) {
        Py_XDECREF(capi_coef2_as_array); }
    }  /* if (capi_coef2_as_array == NULL) ... else of coef2 */
    /* End of cleaning variable coef2 */
    if((PyObject *)capi_alfa2_as_array!=alfa2_capi) {
        Py_XDECREF(capi_alfa2_as_array); }
    }  /* if (capi_alfa2_as_array == NULL) ... else of alfa2 */
    /* End of cleaning variable alfa2 */
    if((PyObject *)capi_shell_type_as_array!=shell_type_capi) {
        Py_XDECREF(capi_shell_type_as_array); }
    }  /* if (capi_shell_type_as_array == NULL) ... else of shell_type */
    /* End of cleaning variable shell_type */
    if((PyObject *)capi_nshell_as_array!=nshell_capi) {
        Py_XDECREF(capi_nshell_as_array); }
    }  /* if (capi_nshell_as_array == NULL) ... else of nshell */
    /* End of cleaning variable nshell */
    }  /* if (capi_CDens_as_array == NULL) ... else of CDens */
    /* End of cleaning variable CDens */
    }  /* if (capi_AlphDens_as_array == NULL) ... else of AlphDens */
    /* End of cleaning variable AlphDens */
    }  /* if (capi_RDens_as_array == NULL) ... else of RDens */
    /* End of cleaning variable RDens */
    }  /* if (capi_iAngDens_as_array == NULL) ... else of iAngDens */
    /* End of cleaning variable iAngDens */
    } /*CHECKSCALAR(len(nprim)>=ntotshell)*/
    } /*if (f2py_success) of ntotshell*/
    /* End of cleaning variable ntotshell */
    } /*CHECKSCALAR(shape(r,0)==nat_2)*/
    } /*if (f2py_success) of nat_2*/
    /* End of cleaning variable nat_2 */
    if((PyObject *)capi_occupancy_as_array!=occupancy_capi) {
        Py_XDECREF(capi_occupancy_as_array); }
    }  /* if (capi_occupancy_as_array == NULL) ... else of occupancy */
    /* End of cleaning variable occupancy */
    if((PyObject *)capi_coef_mol_as_array!=coef_mol_capi) {
        Py_XDECREF(capi_coef_mol_as_array); }
    }  /* if (capi_coef_mol_as_array == NULL) ... else of coef_mol */
    /* End of cleaning variable coef_mol */
    /* End of cleaning variable NDens */
    } /*if (f2py_success) of norbx*/
    /* End of cleaning variable norbx */
    } /*if (f2py_success) of naos*/
    /* End of cleaning variable naos */
    } /*if (f2py_success) of nmos*/
    /* End of cleaning variable nmos */
    } /*if (f2py_success) of TolDens*/
    /* End of cleaning variable TolDens */
    if((PyObject *)capi_nprim_as_array!=nprim_capi) {
        Py_XDECREF(capi_nprim_as_array); }
    }  /* if (capi_nprim_as_array == NULL) ... else of nprim */
    /* End of cleaning variable nprim */
    } /*if (f2py_success) of ldens*/
    /* End of cleaning variable ldens */
    if((PyObject *)capi_r_as_array!=r_capi) {
        Py_XDECREF(capi_r_as_array); }
    }  /* if (capi_r_as_array == NULL) ... else of r */
    /* End of cleaning variable r */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************************** end of build_density ****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"denslib",-1,{{-1}},0,0,(char *)  F_FUNC(denslib,DENSLIB),  (f2py_init_func)f2py_rout_QSYMLIB_denslib,doc_f2py_rout_QSYMLIB_denslib},
    {"center_charge",-1,{{-1}},0,0,(char *)  F_FUNC_US(center_charge,CENTER_CHARGE),  (f2py_init_func)f2py_rout_QSYMLIB_center_charge,doc_f2py_rout_QSYMLIB_center_charge},
    {"build_density",-1,{{-1}},0,0,(char *)  F_FUNC_US(build_density,BUILD_DENSITY),  (f2py_init_func)f2py_rout_QSYMLIB_build_density,doc_f2py_rout_QSYMLIB_build_density},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "QSYMLIB",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_QSYMLIB(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = QSYMLIB_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module QSYMLIB (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.4.2");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'QSYMLIB' is auto-generated with f2py (version:2.4.2).\nFunctions:\n"
"    OutDim,OutCSM_i,OutCSM,OutSymLab,OutSsimilarity = denslib(vaxis_2,vaxis2_2,norbx,igroup,ngroup,dooper,iangdens,alphdens,cdens,rdens,ndens=len(alphdens))\n"
"    elec_total,outrc = center_charge(alphdens,iangdens,rdens,cdens,n_elec,ndens=len(alphdens))\n"
"    iAngDens,AlphDens,CDens,RDens,NDens = build_density(r,ldens,alfa2,coef2,nprim,nshell,shell_type,coef_mol,nmos,naos,norbx,occupancy,TolDens,norb=len(alfa2),nat_2=shape(r,0),ntotshell=len(nprim))\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.4.2");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    QSYMLIB_error = PyErr_NewException ("QSYMLIB.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_QSYMLIB_error", QSYMLIB_error);
    Py_DECREF(QSYMLIB_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }



/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"QSYMLIB");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
