/* File: WFNSYMLIBmodule.c
 * This file is auto-generated with f2py (version:2.4.2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Sun Mar  8 19:01:17 2026
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *WFNSYMLIB_error;
static PyObject *WFNSYMLIB_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = WFNSYMLIB_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = WFNSYMLIB_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(mainlib,MAINLIB)(double*,double*,int*,int*,int*,int*,int*,int*,string*,double*,double*,int*,double*,int*,int*,int*,int*,double*,double*,double*,double*,double*,int*,int*,double*,double*,string*,double*,double*,double*,double*,double*,string*,double*,double*,double*,double*,double*,double*,size_t,size_t,size_t);
extern void F_FUNC(overlap,OVERLAP)(int*,double*,double*,double*);
extern void F_FUNC_US(overlap_mat,OVERLAP_MAT)(double*,string*,double*,int*,int*,int*,int*,int*,int*,int*,double*,double*,size_t);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** mainlib **********************************/
static char doc_f2py_rout_WFNSYMLIB_mainlib[] = "\
OutDim,OutGrim,OutCMS,OutSymLab,OutSDiagA,OutSDiagB,OutWDiagA,OutWDiagB,OutTbl,OutIRLab,OutgIRA,OutgIRB,OutgIRwfA,OutgIRwfB,OutgIRwf,OutSymMat = mainlib(AOccup,BOccup,NBas,NMo,Norb,NAt,NCShell,iZAt,AtLab,Alph,COrb,NShell,RAt,n_prim,shell_type,igroup,ngroup,Ca,Cb,RCread,VAxis,VAxis2,DoOp)\n\nWrapper for ``mainlib``.\
\n\nParameters\n----------\n"
"AOccup : input rank-1 array('d') with bounds (NMo)\n"
"BOccup : input rank-1 array('d') with bounds (NMo)\n"
"NBas : input int\n"
"NMo : input int\n"
"Norb : input int\n"
"NAt : input int\n"
"NCShell : input int\n"
"iZAt : input rank-1 array('i') with bounds (NAt)\n"
"AtLab : input rank-1 array('S') with bounds (NAt)\n"
"Alph : input rank-1 array('d') with bounds (Norb)\n"
"COrb : input rank-1 array('d') with bounds (Norb)\n"
"NShell : input rank-1 array('i') with bounds (NAt)\n"
"RAt : input rank-2 array('d') with bounds (NAt,3)\n"
"n_prim : input rank-1 array('i') with bounds (NCShell)\n"
"shell_type : input rank-1 array('i') with bounds (NCShell)\n"
"igroup : input int\n"
"ngroup : input int\n"
"Ca : input rank-1 array('d') with bounds (NBas * NMo)\n"
"Cb : input rank-1 array('d') with bounds (NBas * NMo)\n"
"RCread : input rank-1 array('d') with bounds (3)\n"
"VAxis : in/output rank-1 array('d') with bounds (3)\n"
"VAxis2 : in/output rank-1 array('d') with bounds (3)\n"
"DoOp : input int\n"
"\nReturns\n-------\n"
"OutDim : rank-1 array('i') with bounds (3)\n"
"OutGrim : rank-1 array('d') with bounds (100)\n"
"OutCMS : rank-1 array('d') with bounds (100)\n"
"OutSymLab : rank-1 array('S') with bounds (100)\n"
"OutSDiagA : rank-2 array('d') with bounds (NMo,100)\n"
"OutSDiagB : rank-2 array('d') with bounds (NMo,100)\n"
"OutWDiagA : rank-1 array('d') with bounds (100)\n"
"OutWDiagB : rank-1 array('d') with bounds (100)\n"
"OutTbl : rank-2 array('d') with bounds (100,100)\n"
"OutIRLab : rank-1 array('S') with bounds (100)\n"
"OutgIRA : rank-2 array('d') with bounds (NMo,100)\n"
"OutgIRB : rank-2 array('d') with bounds (NMo,100)\n"
"OutgIRwfA : rank-1 array('d') with bounds (100)\n"
"OutgIRwfB : rank-1 array('d') with bounds (100)\n"
"OutgIRwf : rank-1 array('d') with bounds (100)\n"
"OutSymMat : rank-3 array('d') with bounds (100,3,3)";
/* extern void F_FUNC(mainlib,MAINLIB)(double*,double*,int*,int*,int*,int*,int*,int*,string*,double*,double*,int*,double*,int*,int*,int*,int*,double*,double*,double*,double*,double*,int*,int*,double*,double*,string*,double*,double*,double*,double*,double*,string*,double*,double*,double*,double*,double*,double*,size_t,size_t,size_t); */
static PyObject *f2py_rout_WFNSYMLIB_mainlib(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,int*,int*,int*,int*,int*,string*,double*,double*,int*,double*,int*,int*,int*,int*,double*,double*,double*,double*,double*,int*,int*,double*,double*,string*,double*,double*,double*,double*,double*,string*,double*,double*,double*,double*,double*,double*,size_t,size_t,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *AOccup = NULL;
    npy_intp AOccup_Dims[1] = {-1};
    const int AOccup_Rank = 1;
    PyArrayObject *capi_AOccup_as_array = NULL;
    int capi_AOccup_intent = 0;
    PyObject *AOccup_capi = Py_None;
    double *BOccup = NULL;
    npy_intp BOccup_Dims[1] = {-1};
    const int BOccup_Rank = 1;
    PyArrayObject *capi_BOccup_as_array = NULL;
    int capi_BOccup_intent = 0;
    PyObject *BOccup_capi = Py_None;
    int NBas = 0;
    PyObject *NBas_capi = Py_None;
    int NMo = 0;
    PyObject *NMo_capi = Py_None;
    int Norb = 0;
    PyObject *Norb_capi = Py_None;
    int NAt = 0;
    PyObject *NAt_capi = Py_None;
    int NCShell = 0;
    PyObject *NCShell_capi = Py_None;
    int *iZAt = NULL;
    npy_intp iZAt_Dims[1] = {-1};
    const int iZAt_Rank = 1;
    PyArrayObject *capi_iZAt_as_array = NULL;
    int capi_iZAt_intent = 0;
    PyObject *iZAt_capi = Py_None;
    string *AtLab = NULL;
    npy_intp AtLab_Dims[1] = {-1};
    const int AtLab_Rank = 1;
    PyArrayObject *capi_AtLab_as_array = NULL;
    int capi_AtLab_intent = 0;
    int slen(AtLab) = 0;
    PyObject *AtLab_capi = Py_None;
    double *Alph = NULL;
    npy_intp Alph_Dims[1] = {-1};
    const int Alph_Rank = 1;
    PyArrayObject *capi_Alph_as_array = NULL;
    int capi_Alph_intent = 0;
    PyObject *Alph_capi = Py_None;
    double *COrb = NULL;
    npy_intp COrb_Dims[1] = {-1};
    const int COrb_Rank = 1;
    PyArrayObject *capi_COrb_as_array = NULL;
    int capi_COrb_intent = 0;
    PyObject *COrb_capi = Py_None;
    int *NShell = NULL;
    npy_intp NShell_Dims[1] = {-1};
    const int NShell_Rank = 1;
    PyArrayObject *capi_NShell_as_array = NULL;
    int capi_NShell_intent = 0;
    PyObject *NShell_capi = Py_None;
    double *RAt = NULL;
    npy_intp RAt_Dims[2] = {-1, -1};
    const int RAt_Rank = 2;
    PyArrayObject *capi_RAt_as_array = NULL;
    int capi_RAt_intent = 0;
    PyObject *RAt_capi = Py_None;
    int *n_prim = NULL;
    npy_intp n_prim_Dims[1] = {-1};
    const int n_prim_Rank = 1;
    PyArrayObject *capi_n_prim_as_array = NULL;
    int capi_n_prim_intent = 0;
    PyObject *n_prim_capi = Py_None;
    int *shell_type = NULL;
    npy_intp shell_type_Dims[1] = {-1};
    const int shell_type_Rank = 1;
    PyArrayObject *capi_shell_type_as_array = NULL;
    int capi_shell_type_intent = 0;
    PyObject *shell_type_capi = Py_None;
    int igroup = 0;
    PyObject *igroup_capi = Py_None;
    int ngroup = 0;
    PyObject *ngroup_capi = Py_None;
    double *Ca = NULL;
    npy_intp Ca_Dims[1] = {-1};
    const int Ca_Rank = 1;
    PyArrayObject *capi_Ca_as_array = NULL;
    int capi_Ca_intent = 0;
    PyObject *Ca_capi = Py_None;
    double *Cb = NULL;
    npy_intp Cb_Dims[1] = {-1};
    const int Cb_Rank = 1;
    PyArrayObject *capi_Cb_as_array = NULL;
    int capi_Cb_intent = 0;
    PyObject *Cb_capi = Py_None;
    double *RCread = NULL;
    npy_intp RCread_Dims[1] = {-1};
    const int RCread_Rank = 1;
    PyArrayObject *capi_RCread_as_array = NULL;
    int capi_RCread_intent = 0;
    PyObject *RCread_capi = Py_None;
    double *VAxis = NULL;
    npy_intp VAxis_Dims[1] = {-1};
    const int VAxis_Rank = 1;
    PyArrayObject *capi_VAxis_as_array = NULL;
    int capi_VAxis_intent = 0;
    PyObject *VAxis_capi = Py_None;
    double *VAxis2 = NULL;
    npy_intp VAxis2_Dims[1] = {-1};
    const int VAxis2_Rank = 1;
    PyArrayObject *capi_VAxis2_as_array = NULL;
    int capi_VAxis2_intent = 0;
    PyObject *VAxis2_capi = Py_None;
    int DoOp = 0;
    PyObject *DoOp_capi = Py_None;
    int *OutDim = NULL;
    npy_intp OutDim_Dims[1] = {-1};
    const int OutDim_Rank = 1;
    PyArrayObject *capi_OutDim_as_array = NULL;
    int capi_OutDim_intent = 0;
    double *OutGrim = NULL;
    npy_intp OutGrim_Dims[1] = {-1};
    const int OutGrim_Rank = 1;
    PyArrayObject *capi_OutGrim_as_array = NULL;
    int capi_OutGrim_intent = 0;
    double *OutCMS = NULL;
    npy_intp OutCMS_Dims[1] = {-1};
    const int OutCMS_Rank = 1;
    PyArrayObject *capi_OutCMS_as_array = NULL;
    int capi_OutCMS_intent = 0;
    string *OutSymLab = NULL;
    npy_intp OutSymLab_Dims[1] = {-1};
    const int OutSymLab_Rank = 1;
    PyArrayObject *capi_OutSymLab_as_array = NULL;
    int capi_OutSymLab_intent = 0;
    int slen(OutSymLab) = 0;
    double *OutSDiagA = NULL;
    npy_intp OutSDiagA_Dims[2] = {-1, -1};
    const int OutSDiagA_Rank = 2;
    PyArrayObject *capi_OutSDiagA_as_array = NULL;
    int capi_OutSDiagA_intent = 0;
    double *OutSDiagB = NULL;
    npy_intp OutSDiagB_Dims[2] = {-1, -1};
    const int OutSDiagB_Rank = 2;
    PyArrayObject *capi_OutSDiagB_as_array = NULL;
    int capi_OutSDiagB_intent = 0;
    double *OutWDiagA = NULL;
    npy_intp OutWDiagA_Dims[1] = {-1};
    const int OutWDiagA_Rank = 1;
    PyArrayObject *capi_OutWDiagA_as_array = NULL;
    int capi_OutWDiagA_intent = 0;
    double *OutWDiagB = NULL;
    npy_intp OutWDiagB_Dims[1] = {-1};
    const int OutWDiagB_Rank = 1;
    PyArrayObject *capi_OutWDiagB_as_array = NULL;
    int capi_OutWDiagB_intent = 0;
    double *OutTbl = NULL;
    npy_intp OutTbl_Dims[2] = {-1, -1};
    const int OutTbl_Rank = 2;
    PyArrayObject *capi_OutTbl_as_array = NULL;
    int capi_OutTbl_intent = 0;
    string *OutIRLab = NULL;
    npy_intp OutIRLab_Dims[1] = {-1};
    const int OutIRLab_Rank = 1;
    PyArrayObject *capi_OutIRLab_as_array = NULL;
    int capi_OutIRLab_intent = 0;
    int slen(OutIRLab) = 0;
    double *OutgIRA = NULL;
    npy_intp OutgIRA_Dims[2] = {-1, -1};
    const int OutgIRA_Rank = 2;
    PyArrayObject *capi_OutgIRA_as_array = NULL;
    int capi_OutgIRA_intent = 0;
    double *OutgIRB = NULL;
    npy_intp OutgIRB_Dims[2] = {-1, -1};
    const int OutgIRB_Rank = 2;
    PyArrayObject *capi_OutgIRB_as_array = NULL;
    int capi_OutgIRB_intent = 0;
    double *OutgIRwfA = NULL;
    npy_intp OutgIRwfA_Dims[1] = {-1};
    const int OutgIRwfA_Rank = 1;
    PyArrayObject *capi_OutgIRwfA_as_array = NULL;
    int capi_OutgIRwfA_intent = 0;
    double *OutgIRwfB = NULL;
    npy_intp OutgIRwfB_Dims[1] = {-1};
    const int OutgIRwfB_Rank = 1;
    PyArrayObject *capi_OutgIRwfB_as_array = NULL;
    int capi_OutgIRwfB_intent = 0;
    double *OutgIRwf = NULL;
    npy_intp OutgIRwf_Dims[1] = {-1};
    const int OutgIRwf_Rank = 1;
    PyArrayObject *capi_OutgIRwf_as_array = NULL;
    int capi_OutgIRwf_intent = 0;
    double *OutSymMat = NULL;
    npy_intp OutSymMat_Dims[3] = {-1, -1, -1};
    const int OutSymMat_Rank = 3;
    PyArrayObject *capi_OutSymMat_as_array = NULL;
    int capi_OutSymMat_intent = 0;
    static char *capi_kwlist[] = {"AOccup","BOccup","NBas","NMo","Norb","NAt","NCShell","iZAt","AtLab","Alph","COrb","NShell","RAt","n_prim","shell_type","igroup","ngroup","Ca","Cb","RCread","VAxis","VAxis2","DoOp",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOOOOOOOOOOO|:WFNSYMLIB.mainlib",\
        capi_kwlist,&AOccup_capi,&BOccup_capi,&NBas_capi,&NMo_capi,&Norb_capi,&NAt_capi,&NCShell_capi,&iZAt_capi,&AtLab_capi,&Alph_capi,&COrb_capi,&NShell_capi,&RAt_capi,&n_prim_capi,&shell_type_capi,&igroup_capi,&ngroup_capi,&Ca_capi,&Cb_capi,&RCread_capi,&VAxis_capi,&VAxis2_capi,&DoOp_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable DoOp */
        DoOp = (int)PyObject_IsTrue(DoOp_capi);
        f2py_success = 1;
    if (f2py_success) {
    /* Processing variable NBas */
        f2py_success = int_from_pyobj(&NBas,NBas_capi,"WFNSYMLIB.mainlib() 3rd argument (NBas) can't be converted to int");
    if (f2py_success) {
    /* Processing variable Norb */
        f2py_success = int_from_pyobj(&Norb,Norb_capi,"WFNSYMLIB.mainlib() 5th argument (Norb) can't be converted to int");
    if (f2py_success) {
    /* Processing variable NAt */
        f2py_success = int_from_pyobj(&NAt,NAt_capi,"WFNSYMLIB.mainlib() 6th argument (NAt) can't be converted to int");
    if (f2py_success) {
    /* Processing variable NCShell */
        f2py_success = int_from_pyobj(&NCShell,NCShell_capi,"WFNSYMLIB.mainlib() 7th argument (NCShell) can't be converted to int");
    if (f2py_success) {
    /* Processing variable igroup */
        f2py_success = int_from_pyobj(&igroup,igroup_capi,"WFNSYMLIB.mainlib() 16th argument (igroup) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ngroup */
        f2py_success = int_from_pyobj(&ngroup,ngroup_capi,"WFNSYMLIB.mainlib() 17th argument (ngroup) can't be converted to int");
    if (f2py_success) {
    /* Processing variable NMo */
        f2py_success = int_from_pyobj(&NMo,NMo_capi,"WFNSYMLIB.mainlib() 4th argument (NMo) can't be converted to int");
    if (f2py_success) {
    /* Processing variable RCread */
    RCread_Dims[0]=3;
    capi_RCread_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the 20th argument `RCread`";
    capi_RCread_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,RCread_Dims,RCread_Rank,  capi_RCread_intent,RCread_capi,capi_errmess);
    if (capi_RCread_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        RCread = (double *)(PyArray_DATA(capi_RCread_as_array));

    /* Processing variable VAxis */
    VAxis_Dims[0]=3;
    capi_VAxis_intent |= F2PY_INTENT_INOUT;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the 21st argument `VAxis`";
    capi_VAxis_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,VAxis_Dims,VAxis_Rank,  capi_VAxis_intent,VAxis_capi,capi_errmess);
    if (capi_VAxis_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        VAxis = (double *)(PyArray_DATA(capi_VAxis_as_array));

    /* Processing variable VAxis2 */
    VAxis2_Dims[0]=3;
    capi_VAxis2_intent |= F2PY_INTENT_INOUT;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the 22nd argument `VAxis2`";
    capi_VAxis2_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,VAxis2_Dims,VAxis2_Rank,  capi_VAxis2_intent,VAxis2_capi,capi_errmess);
    if (capi_VAxis2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        VAxis2 = (double *)(PyArray_DATA(capi_VAxis2_as_array));

    /* Processing variable OutDim */
    OutDim_Dims[0]=3;
    capi_OutDim_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutDim`";
    capi_OutDim_as_array = ndarray_from_pyobj(  NPY_INT,1,OutDim_Dims,OutDim_Rank,  capi_OutDim_intent,Py_None,capi_errmess);
    if (capi_OutDim_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutDim = (int *)(PyArray_DATA(capi_OutDim_as_array));

    /* Processing variable OutCMS */
    OutCMS_Dims[0]=100;
    capi_OutCMS_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutCMS`";
    capi_OutCMS_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,OutCMS_Dims,OutCMS_Rank,  capi_OutCMS_intent,Py_None,capi_errmess);
    if (capi_OutCMS_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutCMS = (double *)(PyArray_DATA(capi_OutCMS_as_array));

    /* Processing variable OutGrim */
    OutGrim_Dims[0]=100;
    capi_OutGrim_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutGrim`";
    capi_OutGrim_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,OutGrim_Dims,OutGrim_Rank,  capi_OutGrim_intent,Py_None,capi_errmess);
    if (capi_OutGrim_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutGrim = (double *)(PyArray_DATA(capi_OutGrim_as_array));

    /* Processing variable OutSymLab */
    OutSymLab_Dims[0]=100;
    capi_OutSymLab_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutSymLab`";
    capi_OutSymLab_as_array = ndarray_from_pyobj(  NPY_STRING,6,OutSymLab_Dims,OutSymLab_Rank,  capi_OutSymLab_intent,Py_None,capi_errmess);
    if (capi_OutSymLab_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutSymLab = (string *)(PyArray_DATA(capi_OutSymLab_as_array));

    slen(OutSymLab) = f2py_itemsize(OutSymLab);
    /* Processing variable OutIRLab */
    OutIRLab_Dims[0]=100;
    capi_OutIRLab_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutIRLab`";
    capi_OutIRLab_as_array = ndarray_from_pyobj(  NPY_STRING,3,OutIRLab_Dims,OutIRLab_Rank,  capi_OutIRLab_intent,Py_None,capi_errmess);
    if (capi_OutIRLab_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutIRLab = (string *)(PyArray_DATA(capi_OutIRLab_as_array));

    slen(OutIRLab) = f2py_itemsize(OutIRLab);
    /* Processing variable OutWDiagA */
    OutWDiagA_Dims[0]=100;
    capi_OutWDiagA_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutWDiagA`";
    capi_OutWDiagA_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,OutWDiagA_Dims,OutWDiagA_Rank,  capi_OutWDiagA_intent,Py_None,capi_errmess);
    if (capi_OutWDiagA_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutWDiagA = (double *)(PyArray_DATA(capi_OutWDiagA_as_array));

    /* Processing variable OutWDiagB */
    OutWDiagB_Dims[0]=100;
    capi_OutWDiagB_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutWDiagB`";
    capi_OutWDiagB_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,OutWDiagB_Dims,OutWDiagB_Rank,  capi_OutWDiagB_intent,Py_None,capi_errmess);
    if (capi_OutWDiagB_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutWDiagB = (double *)(PyArray_DATA(capi_OutWDiagB_as_array));

    /* Processing variable OutTbl */
    OutTbl_Dims[0]=100,OutTbl_Dims[1]=100;
    capi_OutTbl_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutTbl`";
    capi_OutTbl_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,OutTbl_Dims,OutTbl_Rank,  capi_OutTbl_intent,Py_None,capi_errmess);
    if (capi_OutTbl_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutTbl = (double *)(PyArray_DATA(capi_OutTbl_as_array));

    /* Processing variable OutgIRwfA */
    OutgIRwfA_Dims[0]=100;
    capi_OutgIRwfA_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutgIRwfA`";
    capi_OutgIRwfA_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,OutgIRwfA_Dims,OutgIRwfA_Rank,  capi_OutgIRwfA_intent,Py_None,capi_errmess);
    if (capi_OutgIRwfA_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutgIRwfA = (double *)(PyArray_DATA(capi_OutgIRwfA_as_array));

    /* Processing variable OutgIRwfB */
    OutgIRwfB_Dims[0]=100;
    capi_OutgIRwfB_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutgIRwfB`";
    capi_OutgIRwfB_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,OutgIRwfB_Dims,OutgIRwfB_Rank,  capi_OutgIRwfB_intent,Py_None,capi_errmess);
    if (capi_OutgIRwfB_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutgIRwfB = (double *)(PyArray_DATA(capi_OutgIRwfB_as_array));

    /* Processing variable OutgIRwf */
    OutgIRwf_Dims[0]=100;
    capi_OutgIRwf_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutgIRwf`";
    capi_OutgIRwf_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,OutgIRwf_Dims,OutgIRwf_Rank,  capi_OutgIRwf_intent,Py_None,capi_errmess);
    if (capi_OutgIRwf_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutgIRwf = (double *)(PyArray_DATA(capi_OutgIRwf_as_array));

    /* Processing variable OutSymMat */
    OutSymMat_Dims[0]=100,OutSymMat_Dims[1]=3,OutSymMat_Dims[2]=3;
    capi_OutSymMat_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutSymMat`";
    capi_OutSymMat_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,OutSymMat_Dims,OutSymMat_Rank,  capi_OutSymMat_intent,Py_None,capi_errmess);
    if (capi_OutSymMat_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutSymMat = (double *)(PyArray_DATA(capi_OutSymMat_as_array));

    /* Processing variable Ca */
    Ca_Dims[0]=NBas * NMo;
    capi_Ca_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the 18th argument `Ca`";
    capi_Ca_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,Ca_Dims,Ca_Rank,  capi_Ca_intent,Ca_capi,capi_errmess);
    if (capi_Ca_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        Ca = (double *)(PyArray_DATA(capi_Ca_as_array));

    /* Processing variable Cb */
    Cb_Dims[0]=NBas * NMo;
    capi_Cb_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the 19th argument `Cb`";
    capi_Cb_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,Cb_Dims,Cb_Rank,  capi_Cb_intent,Cb_capi,capi_errmess);
    if (capi_Cb_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        Cb = (double *)(PyArray_DATA(capi_Cb_as_array));

    /* Processing variable Alph */
    Alph_Dims[0]=Norb;
    capi_Alph_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the 10th argument `Alph`";
    capi_Alph_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,Alph_Dims,Alph_Rank,  capi_Alph_intent,Alph_capi,capi_errmess);
    if (capi_Alph_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        Alph = (double *)(PyArray_DATA(capi_Alph_as_array));

    /* Processing variable COrb */
    COrb_Dims[0]=Norb;
    capi_COrb_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the 11st argument `COrb`";
    capi_COrb_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,COrb_Dims,COrb_Rank,  capi_COrb_intent,COrb_capi,capi_errmess);
    if (capi_COrb_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        COrb = (double *)(PyArray_DATA(capi_COrb_as_array));

    /* Processing variable RAt */
    RAt_Dims[0]=NAt,RAt_Dims[1]=3;
    capi_RAt_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the 13rd argument `RAt`";
    capi_RAt_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,RAt_Dims,RAt_Rank,  capi_RAt_intent,RAt_capi,capi_errmess);
    if (capi_RAt_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        RAt = (double *)(PyArray_DATA(capi_RAt_as_array));

    /* Processing variable iZAt */
    iZAt_Dims[0]=NAt;
    capi_iZAt_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the 8th argument `iZAt`";
    capi_iZAt_as_array = ndarray_from_pyobj(  NPY_INT,1,iZAt_Dims,iZAt_Rank,  capi_iZAt_intent,iZAt_capi,capi_errmess);
    if (capi_iZAt_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        iZAt = (int *)(PyArray_DATA(capi_iZAt_as_array));

    /* Processing variable NShell */
    NShell_Dims[0]=NAt;
    capi_NShell_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the 12nd argument `NShell`";
    capi_NShell_as_array = ndarray_from_pyobj(  NPY_INT,1,NShell_Dims,NShell_Rank,  capi_NShell_intent,NShell_capi,capi_errmess);
    if (capi_NShell_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        NShell = (int *)(PyArray_DATA(capi_NShell_as_array));

    /* Processing variable n_prim */
    n_prim_Dims[0]=NCShell;
    capi_n_prim_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the 14th argument `n_prim`";
    capi_n_prim_as_array = ndarray_from_pyobj(  NPY_INT,1,n_prim_Dims,n_prim_Rank,  capi_n_prim_intent,n_prim_capi,capi_errmess);
    if (capi_n_prim_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        n_prim = (int *)(PyArray_DATA(capi_n_prim_as_array));

    /* Processing variable shell_type */
    shell_type_Dims[0]=NCShell;
    capi_shell_type_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the 15th argument `shell_type`";
    capi_shell_type_as_array = ndarray_from_pyobj(  NPY_INT,1,shell_type_Dims,shell_type_Rank,  capi_shell_type_intent,shell_type_capi,capi_errmess);
    if (capi_shell_type_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        shell_type = (int *)(PyArray_DATA(capi_shell_type_as_array));

    /* Processing variable AtLab */
    AtLab_Dims[0]=NAt;
    capi_AtLab_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the 9th argument `AtLab`";
    capi_AtLab_as_array = ndarray_from_pyobj(  NPY_STRING,2,AtLab_Dims,AtLab_Rank,  capi_AtLab_intent,AtLab_capi,capi_errmess);
    if (capi_AtLab_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        AtLab = (string *)(PyArray_DATA(capi_AtLab_as_array));

    slen(AtLab) = f2py_itemsize(AtLab);
    /* Processing variable AOccup */
    AOccup_Dims[0]=NMo;
    capi_AOccup_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the 1st argument `AOccup`";
    capi_AOccup_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,AOccup_Dims,AOccup_Rank,  capi_AOccup_intent,AOccup_capi,capi_errmess);
    if (capi_AOccup_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        AOccup = (double *)(PyArray_DATA(capi_AOccup_as_array));

    /* Processing variable BOccup */
    BOccup_Dims[0]=NMo;
    capi_BOccup_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the 2nd argument `BOccup`";
    capi_BOccup_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,BOccup_Dims,BOccup_Rank,  capi_BOccup_intent,BOccup_capi,capi_errmess);
    if (capi_BOccup_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        BOccup = (double *)(PyArray_DATA(capi_BOccup_as_array));

    /* Processing variable OutSDiagA */
    OutSDiagA_Dims[0]=NMo,OutSDiagA_Dims[1]=100;
    capi_OutSDiagA_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutSDiagA`";
    capi_OutSDiagA_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,OutSDiagA_Dims,OutSDiagA_Rank,  capi_OutSDiagA_intent,Py_None,capi_errmess);
    if (capi_OutSDiagA_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutSDiagA = (double *)(PyArray_DATA(capi_OutSDiagA_as_array));

    /* Processing variable OutSDiagB */
    OutSDiagB_Dims[0]=NMo,OutSDiagB_Dims[1]=100;
    capi_OutSDiagB_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutSDiagB`";
    capi_OutSDiagB_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,OutSDiagB_Dims,OutSDiagB_Rank,  capi_OutSDiagB_intent,Py_None,capi_errmess);
    if (capi_OutSDiagB_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutSDiagB = (double *)(PyArray_DATA(capi_OutSDiagB_as_array));

    /* Processing variable OutgIRA */
    OutgIRA_Dims[0]=NMo,OutgIRA_Dims[1]=100;
    capi_OutgIRA_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutgIRA`";
    capi_OutgIRA_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,OutgIRA_Dims,OutgIRA_Rank,  capi_OutgIRA_intent,Py_None,capi_errmess);
    if (capi_OutgIRA_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutgIRA = (double *)(PyArray_DATA(capi_OutgIRA_as_array));

    /* Processing variable OutgIRB */
    OutgIRB_Dims[0]=NMo,OutgIRB_Dims[1]=100;
    capi_OutgIRB_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.mainlib: failed to create array from the hidden `OutgIRB`";
    capi_OutgIRB_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,OutgIRB_Dims,OutgIRB_Rank,  capi_OutgIRB_intent,Py_None,capi_errmess);
    if (capi_OutgIRB_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        OutgIRB = (double *)(PyArray_DATA(capi_OutgIRB_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(AOccup,BOccup,&NBas,&NMo,&Norb,&NAt,&NCShell,iZAt,AtLab,Alph,COrb,NShell,RAt,n_prim,shell_type,&igroup,&ngroup,Ca,Cb,RCread,VAxis,VAxis2,&DoOp,OutDim,OutGrim,OutCMS,OutSymLab,OutSDiagA,OutSDiagB,OutWDiagA,OutWDiagB,OutTbl,OutIRLab,OutgIRA,OutgIRB,OutgIRwfA,OutgIRwfB,OutgIRwf,OutSymMat,slen(AtLab),slen(OutSymLab),slen(OutIRLab));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NNNNNNNNNNNNNNNN",capi_OutDim_as_array,capi_OutGrim_as_array,capi_OutCMS_as_array,capi_OutSymLab_as_array,capi_OutSDiagA_as_array,capi_OutSDiagB_as_array,capi_OutWDiagA_as_array,capi_OutWDiagB_as_array,capi_OutTbl_as_array,capi_OutIRLab_as_array,capi_OutgIRA_as_array,capi_OutgIRB_as_array,capi_OutgIRwfA_as_array,capi_OutgIRwfB_as_array,capi_OutgIRwf_as_array,capi_OutSymMat_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_OutgIRB_as_array == NULL) ... else of OutgIRB */
    /* End of cleaning variable OutgIRB */
    }  /* if (capi_OutgIRA_as_array == NULL) ... else of OutgIRA */
    /* End of cleaning variable OutgIRA */
    }  /* if (capi_OutSDiagB_as_array == NULL) ... else of OutSDiagB */
    /* End of cleaning variable OutSDiagB */
    }  /* if (capi_OutSDiagA_as_array == NULL) ... else of OutSDiagA */
    /* End of cleaning variable OutSDiagA */
    if((PyObject *)capi_BOccup_as_array!=BOccup_capi) {
        Py_XDECREF(capi_BOccup_as_array); }
    }  /* if (capi_BOccup_as_array == NULL) ... else of BOccup */
    /* End of cleaning variable BOccup */
    if((PyObject *)capi_AOccup_as_array!=AOccup_capi) {
        Py_XDECREF(capi_AOccup_as_array); }
    }  /* if (capi_AOccup_as_array == NULL) ... else of AOccup */
    /* End of cleaning variable AOccup */
    if((PyObject *)capi_AtLab_as_array!=AtLab_capi) {
        Py_XDECREF(capi_AtLab_as_array); }
    }  /* if (capi_AtLab_as_array == NULL) ... else of AtLab */
    /* End of cleaning variable AtLab */
    if((PyObject *)capi_shell_type_as_array!=shell_type_capi) {
        Py_XDECREF(capi_shell_type_as_array); }
    }  /* if (capi_shell_type_as_array == NULL) ... else of shell_type */
    /* End of cleaning variable shell_type */
    if((PyObject *)capi_n_prim_as_array!=n_prim_capi) {
        Py_XDECREF(capi_n_prim_as_array); }
    }  /* if (capi_n_prim_as_array == NULL) ... else of n_prim */
    /* End of cleaning variable n_prim */
    if((PyObject *)capi_NShell_as_array!=NShell_capi) {
        Py_XDECREF(capi_NShell_as_array); }
    }  /* if (capi_NShell_as_array == NULL) ... else of NShell */
    /* End of cleaning variable NShell */
    if((PyObject *)capi_iZAt_as_array!=iZAt_capi) {
        Py_XDECREF(capi_iZAt_as_array); }
    }  /* if (capi_iZAt_as_array == NULL) ... else of iZAt */
    /* End of cleaning variable iZAt */
    if((PyObject *)capi_RAt_as_array!=RAt_capi) {
        Py_XDECREF(capi_RAt_as_array); }
    }  /* if (capi_RAt_as_array == NULL) ... else of RAt */
    /* End of cleaning variable RAt */
    if((PyObject *)capi_COrb_as_array!=COrb_capi) {
        Py_XDECREF(capi_COrb_as_array); }
    }  /* if (capi_COrb_as_array == NULL) ... else of COrb */
    /* End of cleaning variable COrb */
    if((PyObject *)capi_Alph_as_array!=Alph_capi) {
        Py_XDECREF(capi_Alph_as_array); }
    }  /* if (capi_Alph_as_array == NULL) ... else of Alph */
    /* End of cleaning variable Alph */
    if((PyObject *)capi_Cb_as_array!=Cb_capi) {
        Py_XDECREF(capi_Cb_as_array); }
    }  /* if (capi_Cb_as_array == NULL) ... else of Cb */
    /* End of cleaning variable Cb */
    if((PyObject *)capi_Ca_as_array!=Ca_capi) {
        Py_XDECREF(capi_Ca_as_array); }
    }  /* if (capi_Ca_as_array == NULL) ... else of Ca */
    /* End of cleaning variable Ca */
    }  /* if (capi_OutSymMat_as_array == NULL) ... else of OutSymMat */
    /* End of cleaning variable OutSymMat */
    }  /* if (capi_OutgIRwf_as_array == NULL) ... else of OutgIRwf */
    /* End of cleaning variable OutgIRwf */
    }  /* if (capi_OutgIRwfB_as_array == NULL) ... else of OutgIRwfB */
    /* End of cleaning variable OutgIRwfB */
    }  /* if (capi_OutgIRwfA_as_array == NULL) ... else of OutgIRwfA */
    /* End of cleaning variable OutgIRwfA */
    }  /* if (capi_OutTbl_as_array == NULL) ... else of OutTbl */
    /* End of cleaning variable OutTbl */
    }  /* if (capi_OutWDiagB_as_array == NULL) ... else of OutWDiagB */
    /* End of cleaning variable OutWDiagB */
    }  /* if (capi_OutWDiagA_as_array == NULL) ... else of OutWDiagA */
    /* End of cleaning variable OutWDiagA */
    }  /* if (capi_OutIRLab_as_array == NULL) ... else of OutIRLab */
    /* End of cleaning variable OutIRLab */
    }  /* if (capi_OutSymLab_as_array == NULL) ... else of OutSymLab */
    /* End of cleaning variable OutSymLab */
    }  /* if (capi_OutGrim_as_array == NULL) ... else of OutGrim */
    /* End of cleaning variable OutGrim */
    }  /* if (capi_OutCMS_as_array == NULL) ... else of OutCMS */
    /* End of cleaning variable OutCMS */
    }  /* if (capi_OutDim_as_array == NULL) ... else of OutDim */
    /* End of cleaning variable OutDim */
    if((PyObject *)capi_VAxis2_as_array!=VAxis2_capi) {
        Py_XDECREF(capi_VAxis2_as_array); }
    }  /* if (capi_VAxis2_as_array == NULL) ... else of VAxis2 */
    /* End of cleaning variable VAxis2 */
    if((PyObject *)capi_VAxis_as_array!=VAxis_capi) {
        Py_XDECREF(capi_VAxis_as_array); }
    }  /* if (capi_VAxis_as_array == NULL) ... else of VAxis */
    /* End of cleaning variable VAxis */
    if((PyObject *)capi_RCread_as_array!=RCread_capi) {
        Py_XDECREF(capi_RCread_as_array); }
    }  /* if (capi_RCread_as_array == NULL) ... else of RCread */
    /* End of cleaning variable RCread */
    } /*if (f2py_success) of NMo*/
    /* End of cleaning variable NMo */
    } /*if (f2py_success) of ngroup*/
    /* End of cleaning variable ngroup */
    } /*if (f2py_success) of igroup*/
    /* End of cleaning variable igroup */
    } /*if (f2py_success) of NCShell*/
    /* End of cleaning variable NCShell */
    } /*if (f2py_success) of NAt*/
    /* End of cleaning variable NAt */
    } /*if (f2py_success) of Norb*/
    /* End of cleaning variable Norb */
    } /*if (f2py_success) of NBas*/
    /* End of cleaning variable NBas */
    } /*if (f2py_success) of DoOp*/
    /* End of cleaning variable DoOp */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of mainlib *******************************/

/********************************** overlap **********************************/
static char doc_f2py_rout_WFNSYMLIB_overlap[] = "\
integral = overlap(i_angl,exponent,R)\n\nWrapper for ``overlap``.\
\n\nParameters\n----------\n"
"i_angl : input rank-1 array('i') with bounds (3)\n"
"exponent : input float\n"
"R : input rank-1 array('d') with bounds (3)\n"
"\nReturns\n-------\n"
"integral : float";
/* extern void F_FUNC(overlap,OVERLAP)(int*,double*,double*,double*); */
static PyObject *f2py_rout_WFNSYMLIB_overlap(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int *i_angl = NULL;
    npy_intp i_angl_Dims[1] = {-1};
    const int i_angl_Rank = 1;
    PyArrayObject *capi_i_angl_as_array = NULL;
    int capi_i_angl_intent = 0;
    PyObject *i_angl_capi = Py_None;
    double exponent = 0;
    PyObject *exponent_capi = Py_None;
    double *R = NULL;
    npy_intp R_Dims[1] = {-1};
    const int R_Rank = 1;
    PyArrayObject *capi_R_as_array = NULL;
    int capi_R_intent = 0;
    PyObject *R_capi = Py_None;
    double integral = 0;
    static char *capi_kwlist[] = {"i_angl","exponent","R",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:WFNSYMLIB.overlap",\
        capi_kwlist,&i_angl_capi,&exponent_capi,&R_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable i_angl */
    i_angl_Dims[0]=3;
    capi_i_angl_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.overlap: failed to create array from the 1st argument `i_angl`";
    capi_i_angl_as_array = ndarray_from_pyobj(  NPY_INT,1,i_angl_Dims,i_angl_Rank,  capi_i_angl_intent,i_angl_capi,capi_errmess);
    if (capi_i_angl_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        i_angl = (int *)(PyArray_DATA(capi_i_angl_as_array));

    /* Processing variable R */
    R_Dims[0]=3;
    capi_R_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.overlap: failed to create array from the 3rd argument `R`";
    capi_R_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,R_Dims,R_Rank,  capi_R_intent,R_capi,capi_errmess);
    if (capi_R_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        R = (double *)(PyArray_DATA(capi_R_as_array));

    /* Processing variable exponent */
        f2py_success = double_from_pyobj(&exponent,exponent_capi,"WFNSYMLIB.overlap() 2nd argument (exponent) can't be converted to double");
    if (f2py_success) {
    /* Processing variable integral */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(i_angl,&exponent,R,&integral);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",integral);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable integral */
    } /*if (f2py_success) of exponent*/
    /* End of cleaning variable exponent */
    if((PyObject *)capi_R_as_array!=R_capi) {
        Py_XDECREF(capi_R_as_array); }
    }  /* if (capi_R_as_array == NULL) ... else of R */
    /* End of cleaning variable R */
    if((PyObject *)capi_i_angl_as_array!=i_angl_capi) {
        Py_XDECREF(capi_i_angl_as_array); }
    }  /* if (capi_i_angl_as_array == NULL) ... else of i_angl */
    /* End of cleaning variable i_angl */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of overlap *******************************/

/******************************** overlap_mat ********************************/
static char doc_f2py_rout_WFNSYMLIB_overlap_mat[] = "\
S_AO = overlap_mat(AtLab,RAt,NBas,NAt,NOrb,NCShell,NShell,shell_type,n_prim,COrb,Alph)\n\nWrapper for ``overlap_mat``.\
\n\nParameters\n----------\n"
"AtLab : input rank-1 array('S') with bounds (NAt)\n"
"RAt : input rank-2 array('d') with bounds (NAt,3)\n"
"NBas : input int\n"
"NAt : input int\n"
"NOrb : input int\n"
"NCShell : input int\n"
"NShell : input rank-1 array('i') with bounds (NAt)\n"
"shell_type : input rank-1 array('i') with bounds (NCShell)\n"
"n_prim : input rank-1 array('i') with bounds (NCShell)\n"
"COrb : input rank-1 array('d') with bounds (NOrb)\n"
"Alph : input rank-1 array('d') with bounds (NOrb)\n"
"\nReturns\n-------\n"
"S_AO : rank-1 array('d') with bounds (NBas * NBas)";
/* extern void F_FUNC_US(overlap_mat,OVERLAP_MAT)(double*,string*,double*,int*,int*,int*,int*,int*,int*,int*,double*,double*,size_t); */
static PyObject *f2py_rout_WFNSYMLIB_overlap_mat(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,string*,double*,int*,int*,int*,int*,int*,int*,int*,double*,double*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *S_AO = NULL;
    npy_intp S_AO_Dims[1] = {-1};
    const int S_AO_Rank = 1;
    PyArrayObject *capi_S_AO_as_array = NULL;
    int capi_S_AO_intent = 0;
    string *AtLab = NULL;
    npy_intp AtLab_Dims[1] = {-1};
    const int AtLab_Rank = 1;
    PyArrayObject *capi_AtLab_as_array = NULL;
    int capi_AtLab_intent = 0;
    int slen(AtLab) = 0;
    PyObject *AtLab_capi = Py_None;
    double *RAt = NULL;
    npy_intp RAt_Dims[2] = {-1, -1};
    const int RAt_Rank = 2;
    PyArrayObject *capi_RAt_as_array = NULL;
    int capi_RAt_intent = 0;
    PyObject *RAt_capi = Py_None;
    int NBas = 0;
    PyObject *NBas_capi = Py_None;
    int NAt = 0;
    PyObject *NAt_capi = Py_None;
    int NOrb = 0;
    PyObject *NOrb_capi = Py_None;
    int NCShell = 0;
    PyObject *NCShell_capi = Py_None;
    int *NShell = NULL;
    npy_intp NShell_Dims[1] = {-1};
    const int NShell_Rank = 1;
    PyArrayObject *capi_NShell_as_array = NULL;
    int capi_NShell_intent = 0;
    PyObject *NShell_capi = Py_None;
    int *shell_type = NULL;
    npy_intp shell_type_Dims[1] = {-1};
    const int shell_type_Rank = 1;
    PyArrayObject *capi_shell_type_as_array = NULL;
    int capi_shell_type_intent = 0;
    PyObject *shell_type_capi = Py_None;
    int *n_prim = NULL;
    npy_intp n_prim_Dims[1] = {-1};
    const int n_prim_Rank = 1;
    PyArrayObject *capi_n_prim_as_array = NULL;
    int capi_n_prim_intent = 0;
    PyObject *n_prim_capi = Py_None;
    double *COrb = NULL;
    npy_intp COrb_Dims[1] = {-1};
    const int COrb_Rank = 1;
    PyArrayObject *capi_COrb_as_array = NULL;
    int capi_COrb_intent = 0;
    PyObject *COrb_capi = Py_None;
    double *Alph = NULL;
    npy_intp Alph_Dims[1] = {-1};
    const int Alph_Rank = 1;
    PyArrayObject *capi_Alph_as_array = NULL;
    int capi_Alph_intent = 0;
    PyObject *Alph_capi = Py_None;
    static char *capi_kwlist[] = {"AtLab","RAt","NBas","NAt","NOrb","NCShell","NShell","shell_type","n_prim","COrb","Alph",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOO|:WFNSYMLIB.overlap_mat",\
        capi_kwlist,&AtLab_capi,&RAt_capi,&NBas_capi,&NAt_capi,&NOrb_capi,&NCShell_capi,&NShell_capi,&shell_type_capi,&n_prim_capi,&COrb_capi,&Alph_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable NBas */
        f2py_success = int_from_pyobj(&NBas,NBas_capi,"WFNSYMLIB.overlap_mat() 3rd argument (NBas) can't be converted to int");
    if (f2py_success) {
    /* Processing variable NAt */
        f2py_success = int_from_pyobj(&NAt,NAt_capi,"WFNSYMLIB.overlap_mat() 4th argument (NAt) can't be converted to int");
    if (f2py_success) {
    /* Processing variable NCShell */
        f2py_success = int_from_pyobj(&NCShell,NCShell_capi,"WFNSYMLIB.overlap_mat() 6th argument (NCShell) can't be converted to int");
    if (f2py_success) {
    /* Processing variable NOrb */
        f2py_success = int_from_pyobj(&NOrb,NOrb_capi,"WFNSYMLIB.overlap_mat() 5th argument (NOrb) can't be converted to int");
    if (f2py_success) {
    /* Processing variable S_AO */
    S_AO_Dims[0]=NBas * NBas;
    capi_S_AO_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.overlap_mat: failed to create array from the hidden `S_AO`";
    capi_S_AO_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,S_AO_Dims,S_AO_Rank,  capi_S_AO_intent,Py_None,capi_errmess);
    if (capi_S_AO_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        S_AO = (double *)(PyArray_DATA(capi_S_AO_as_array));

    /* Processing variable AtLab */
    AtLab_Dims[0]=NAt;
    capi_AtLab_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.overlap_mat: failed to create array from the 1st argument `AtLab`";
    capi_AtLab_as_array = ndarray_from_pyobj(  NPY_STRING,2,AtLab_Dims,AtLab_Rank,  capi_AtLab_intent,AtLab_capi,capi_errmess);
    if (capi_AtLab_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        AtLab = (string *)(PyArray_DATA(capi_AtLab_as_array));

    slen(AtLab) = f2py_itemsize(AtLab);
    /* Processing variable RAt */
    RAt_Dims[0]=NAt,RAt_Dims[1]=3;
    capi_RAt_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.overlap_mat: failed to create array from the 2nd argument `RAt`";
    capi_RAt_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,RAt_Dims,RAt_Rank,  capi_RAt_intent,RAt_capi,capi_errmess);
    if (capi_RAt_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        RAt = (double *)(PyArray_DATA(capi_RAt_as_array));

    /* Processing variable NShell */
    NShell_Dims[0]=NAt;
    capi_NShell_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.overlap_mat: failed to create array from the 7th argument `NShell`";
    capi_NShell_as_array = ndarray_from_pyobj(  NPY_INT,1,NShell_Dims,NShell_Rank,  capi_NShell_intent,NShell_capi,capi_errmess);
    if (capi_NShell_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        NShell = (int *)(PyArray_DATA(capi_NShell_as_array));

    /* Processing variable n_prim */
    n_prim_Dims[0]=NCShell;
    capi_n_prim_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.overlap_mat: failed to create array from the 9th argument `n_prim`";
    capi_n_prim_as_array = ndarray_from_pyobj(  NPY_INT,1,n_prim_Dims,n_prim_Rank,  capi_n_prim_intent,n_prim_capi,capi_errmess);
    if (capi_n_prim_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        n_prim = (int *)(PyArray_DATA(capi_n_prim_as_array));

    /* Processing variable shell_type */
    shell_type_Dims[0]=NCShell;
    capi_shell_type_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.overlap_mat: failed to create array from the 8th argument `shell_type`";
    capi_shell_type_as_array = ndarray_from_pyobj(  NPY_INT,1,shell_type_Dims,shell_type_Rank,  capi_shell_type_intent,shell_type_capi,capi_errmess);
    if (capi_shell_type_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        shell_type = (int *)(PyArray_DATA(capi_shell_type_as_array));

    /* Processing variable Alph */
    Alph_Dims[0]=NOrb;
    capi_Alph_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.overlap_mat: failed to create array from the 11st argument `Alph`";
    capi_Alph_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,Alph_Dims,Alph_Rank,  capi_Alph_intent,Alph_capi,capi_errmess);
    if (capi_Alph_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        Alph = (double *)(PyArray_DATA(capi_Alph_as_array));

    /* Processing variable COrb */
    COrb_Dims[0]=NOrb;
    capi_COrb_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "WFNSYMLIB.WFNSYMLIB.overlap_mat: failed to create array from the 10th argument `COrb`";
    capi_COrb_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,COrb_Dims,COrb_Rank,  capi_COrb_intent,COrb_capi,capi_errmess);
    if (capi_COrb_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = WFNSYMLIB_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        COrb = (double *)(PyArray_DATA(capi_COrb_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(S_AO,AtLab,RAt,&NBas,&NAt,&NOrb,&NCShell,NShell,shell_type,n_prim,COrb,Alph,slen(AtLab));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_S_AO_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_COrb_as_array!=COrb_capi) {
        Py_XDECREF(capi_COrb_as_array); }
    }  /* if (capi_COrb_as_array == NULL) ... else of COrb */
    /* End of cleaning variable COrb */
    if((PyObject *)capi_Alph_as_array!=Alph_capi) {
        Py_XDECREF(capi_Alph_as_array); }
    }  /* if (capi_Alph_as_array == NULL) ... else of Alph */
    /* End of cleaning variable Alph */
    if((PyObject *)capi_shell_type_as_array!=shell_type_capi) {
        Py_XDECREF(capi_shell_type_as_array); }
    }  /* if (capi_shell_type_as_array == NULL) ... else of shell_type */
    /* End of cleaning variable shell_type */
    if((PyObject *)capi_n_prim_as_array!=n_prim_capi) {
        Py_XDECREF(capi_n_prim_as_array); }
    }  /* if (capi_n_prim_as_array == NULL) ... else of n_prim */
    /* End of cleaning variable n_prim */
    if((PyObject *)capi_NShell_as_array!=NShell_capi) {
        Py_XDECREF(capi_NShell_as_array); }
    }  /* if (capi_NShell_as_array == NULL) ... else of NShell */
    /* End of cleaning variable NShell */
    if((PyObject *)capi_RAt_as_array!=RAt_capi) {
        Py_XDECREF(capi_RAt_as_array); }
    }  /* if (capi_RAt_as_array == NULL) ... else of RAt */
    /* End of cleaning variable RAt */
    if((PyObject *)capi_AtLab_as_array!=AtLab_capi) {
        Py_XDECREF(capi_AtLab_as_array); }
    }  /* if (capi_AtLab_as_array == NULL) ... else of AtLab */
    /* End of cleaning variable AtLab */
    }  /* if (capi_S_AO_as_array == NULL) ... else of S_AO */
    /* End of cleaning variable S_AO */
    } /*if (f2py_success) of NOrb*/
    /* End of cleaning variable NOrb */
    } /*if (f2py_success) of NCShell*/
    /* End of cleaning variable NCShell */
    } /*if (f2py_success) of NAt*/
    /* End of cleaning variable NAt */
    } /*if (f2py_success) of NBas*/
    /* End of cleaning variable NBas */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of overlap_mat *****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"mainlib",-1,{{-1}},0,0,(char *)  F_FUNC(mainlib,MAINLIB),  (f2py_init_func)f2py_rout_WFNSYMLIB_mainlib,doc_f2py_rout_WFNSYMLIB_mainlib},
    {"overlap",-1,{{-1}},0,0,(char *)  F_FUNC(overlap,OVERLAP),  (f2py_init_func)f2py_rout_WFNSYMLIB_overlap,doc_f2py_rout_WFNSYMLIB_overlap},
    {"overlap_mat",-1,{{-1}},0,0,(char *)  F_FUNC_US(overlap_mat,OVERLAP_MAT),  (f2py_init_func)f2py_rout_WFNSYMLIB_overlap_mat,doc_f2py_rout_WFNSYMLIB_overlap_mat},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "WFNSYMLIB",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_WFNSYMLIB(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = WFNSYMLIB_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module WFNSYMLIB (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.4.2");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'WFNSYMLIB' is auto-generated with f2py (version:2.4.2).\nFunctions:\n"
"    OutDim,OutGrim,OutCMS,OutSymLab,OutSDiagA,OutSDiagB,OutWDiagA,OutWDiagB,OutTbl,OutIRLab,OutgIRA,OutgIRB,OutgIRwfA,OutgIRwfB,OutgIRwf,OutSymMat = mainlib(AOccup,BOccup,NBas,NMo,Norb,NAt,NCShell,iZAt,AtLab,Alph,COrb,NShell,RAt,n_prim,shell_type,igroup,ngroup,Ca,Cb,RCread,VAxis,VAxis2,DoOp)\n"
"    integral = overlap(i_angl,exponent,R)\n"
"    S_AO = overlap_mat(AtLab,RAt,NBas,NAt,NOrb,NCShell,NShell,shell_type,n_prim,COrb,Alph)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.4.2");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    WFNSYMLIB_error = PyErr_NewException ("WFNSYMLIB.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_WFNSYMLIB_error", WFNSYMLIB_error);
    Py_DECREF(WFNSYMLIB_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }



/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"WFNSYMLIB");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
